### ISSUE TITLE
dupe bug when (dis)assembling a ship that has copycat blocks

### ISSUE THREAD

**Issue by imaradio** [ValkyrienSkies/Eureka#375]
### Mod Name

Create

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.19

### Mod Loader

Fabric

### Issue description

if copycat blocks are on a ship, when assembling or disassembling said ship, the blocks that were used in the copycat blocks will duplicate by dropping as items

a video demonstrating the above: https://filebin.net/mgvj6wnlpi6n5se7

i expect it to instead not drop the blocks used in the copycat blocks

### Issue reproduction

1. make a ship that has either a copycat step or copycat panel on it
2. put a block that you wish to duplicate in the copycat step or panel
3. assemble or disassemble the ship

### Logs

[latest.log](https://github.com/user-attachments/files/15889096/latest.log)
couldnt find a debug.log

**Comment by intervinn** [comment]
having the same issue here on forge


https://github.com/ValkyrienSkies/Eureka/assets/69168328/32632f12-76d9-408b-b597-118fb903fe0c

**Comment by notnate75** [comment]
Same issue here as well.... 

never thought of using diamond blocks... hmmm

**Comment by PriestOfFern** [comment]
This is already fixed on the VS2 github, as well as every other custom container assembly dupe glitch

**Comment by notnate75** [comment]
hmm this is what i have and it is still happening to me.
![image](https://github.com/user-attachments/assets/c3519241-0e53-46cd-8389-9f5f87709923)

**Comment by thetheaplant** [comment]
That is not the github version, you'd have to build the github version yourself to get that feature.

**Comment by notnate75** [comment]
then it is not distributed?  sorry, i am not a programmer;  i don't know what you mean by "build the github version yourself" or how to do it.  looking at the VS2 github they have a link to download the mod from their website and that one is the same version i have right from CF.   so for us non-programmer type modders it is not "fixed" imho.

**Comment by thetheaplant** [comment]
It has not been distributed, no, if you really need it, you can get it from here. It will likely be distributed after Ruby is done working on VS-Core.

**Comment by notnate75** [comment]
its cool for now, i was just being told it was fixed after trying to add some information to bug reporting.  my ship is currently under construction anyway and this will not be a huge issue for some time so i can wait.  it is great to know they have a fix figured out and now i have something to look forward to :D thanks!

**Comment by n01d3a5** [comment]
is it distributed by now?

**Comment by imaradio** [comment]
@n01d3a5 the last release was made in [may 2024](https://github.com/ValkyrienSkies/Eureka/releases/tag/release%2F1.5.1-beta.1), and has the same version number as that shown in notnate75's comment, so no it hasnt been distributed

ill close this report since the bug has seemingly been fixed just not distributed
